### ISSUE TITLE
Link to hosted online version is broken

### ISSUE THREAD

**Issue by boaz-amit** [videlalvaro/connstring_to_amqp#2]
It seems the link to the hosted online app in the README file is broken.

For the time being there's an alternative here: _link removed_

~The alternative is hosted at codepen.io and is essentially the same source code, except minor adjustments to give credit to the source repository and creator.~

**Comment by videlalvaro** [comment]
I updated the README to point to the new location https://amqpconnconverter.github.io/

@boaz-amit Please remove that Codepen.

**Comment by boaz-amit** [comment]
@videlalvaro Thanks for the prompt response! Deleted the Codepen and edited the original message to remove the link as well.

**Comment by videlalvaro** [comment]
BTW @boaz-amit may I ask what are you using this integration for?

**Comment by boaz-amit** [comment]
@videlalvaro We use it for configuring RabbitMQ shovels to Azure Event Hubs.
